<?php
$themename = "Vigilance";
$shortname = "V";
$options = array(
	
				array(	"name" => __('Custom Logo Image <a href="https://themes.jestro.com/members/signup.php"><em>PRO Feature</em></a>', 'vigilance'),
								"type" => "subhead"),
        
        array(	"name" => __('Enable custom logo image', 'vigilance'),
					    	"id" => $shortname."_logo",
								"desc" => __('Check this box to use a custom logo.', 'vigilance'),
					    	"std" => __('false', 'vigilance'),
					    	"type" => "checkbox"),
        
        array(  "name" => __('Logo image file name', 'vigilance'),
              	"id" => $shortname."_logo_img",
              	"desc" => __('Place your images in the <code>/wp-content/themes/vigilance/images</code> subdirectory', 'vigilance'),
              	"std" => "",
              	"type" => "text"),
            
        array(  "name" => __('Logo image ALT tag', 'vigilance'),
              	"id" => $shortname."_logo_img_alt",
              	"desc" => __('An alt tag for your logo image. Important for SEO.', 'vigilance'),
              	"std" => "",
              	"type" => "text"),
              
        array( 	"name" => __('Display tagline', 'vigilance'),
					   		"id" => $shortname."_tagline",
								"desc" => __('Check this box to show your tagline below your logo.', 'vigilance'),
					    	"std" => __('false', 'vigilance'),
					    	"type" => "checkbox"),
                    
        array(	"name" => __('Navigation', 'vigilance'),
								"type" => "subhead"),
        
        array(  "name" => __('Exclude pages from header', 'vigilance'),
              	"id" => $shortname."_pages_to_exclude",
              	"desc" => __('Pages you wish to exclude from your top navigation. Use the page ID in a comma-delimited list (eg. 1,2,3)', 'vigilance'),
              	"std" => "",
              	"type" => "text"),
              
        array(	"name" => __('Color Scheme', 'vigilance'),
								"type" => "subhead"),
            
        array(	"name" => __('Customize colors', 'vigilance'),
								"id" => $shortname."_background_css",
								"desc" => __('If enabled the theme will use the layouts and colors you choose below.', 'vigilance'),	
					    	"std" => __('Disabled', 'vigilance'),
					    	"type" => "select",
								"options" => array( "disabled" => __('Disabled', 'vigilance'), "enabled"  =>  __('Enabled', 'vigilance'))),
              
        array(	"name" => __('Background color', 'vigilance'),
					    	"id" => $shortname."_background_color",
								"desc" => __('Your background color. Use Hex values and leave out the leading #.', 'vigilance'),
					    	"std" => "dcdfc2",
								"type" => "text"),
        
        array(	"name" => __('Border color', 'vigilance'),
					    	"id" => $shortname."_border_color",
								"desc" => __('Your border color. Use Hex values and leave out the leading #.', 'vigilance'),
					    	"std" => "d7dab9",
					    	"type" => "text"),
        
        array(	"name" => __('Link color', 'vigilance'),
					    	"id" => $shortname."_link_color",
								"desc" => __('Your link color. Use Hex values and leave out the leading #.', 'vigilance'),
					    	"std" => "772124",
					    	"type" => "text"),
        
        array(	"name" => __('Link hover color', 'vigilance'),
					    	"id" => $shortname."_hover_color",
								"desc" => __('Your link hover color. Use Hex values and leave out the leading #.', 'vigilance'),
					    	"std" => "58181b",
					    	"type" => "text"),
         
        array(	"name" => __('Disable hover images', 'vigilance'),
					    	"id" => $shortname."_image_hover",
								"desc" => __('This is useful if you use custom link colors and do not want the default red showing when a user hovers over the comments bubble or the sidebar menu items.', 'vigilance'),
					    	"std" => __('false', 'vigilance'),
					    	"type" => "checkbox"),
              
				array(	"name" => __('Top Banner Image', 'vigilance'),
								"type" => "subhead"),

				array(	"name" => __('Banner state', 'vigilance'),
								"id" => $shortname."_banner_state",
								"desc" => __('Place your images in the <code>/wp-content/themes/vigilance/images/top-banner</code> subdirectory and they will be added to the rotation. <br /><a href="http://themes.jestro.com/tutorials/vigilance.htm#options-banner">Read this for page and post specific images.</a>', 'vigilance'),
			    			"std" => __('Rotating images', 'vigilance'),
			    			"type" => "select",
			    			"options" => array( "rotate" => __('Rotating images', 'vigilance'), "static" => __('Static image', 'vigilance'), "custom" => __('Custom code', 'vigilance'), "hide" => __('Do not show an image', 'vigilance'))),
        
        array(	"name" => __('Banner height', 'vigilance'),
					    	"id" => $shortname."_banner_height",
								"desc" => __('The height of your image. The width is fixed at 596px.', 'vigilance'),
					    	"std" => "125",
					    	"type" => "text"),
        
        array(	"name" => __('Banner alt tag', 'vigilance'),
					    	"id" => $shortname."_banner_alt",
								"desc" => __('The alt tag for your banner image(s). Will default to your blog title if left blank.', 'vigilance'),
					    	"std" => "",
					    	"type" => "textarea",
              	"type" => "text"),
        
        array(	"name" => __('Static image', 'vigilance'),
					    	"id" => $shortname."_banner_url",
								"desc" => __('Replace your top banner with a static image.<br /><strong>Note:</strong> You must upload this image to <code>/wp-content/themes/vigilance/images/top-banner</code> <strong>and</strong> the <em>Banner State</em> must be set to "Static Image" for this to work.', 'vigilance'),
					    	"std" => "",
					    	"type" => "text"),
              
        array(	"name" => __('Home image', 'vigilance'),
					    	"id" => $shortname."_banner_home",
								"desc" => __('Replace your home top banner with a specific image.<br /><strong>Note:</strong> You must upload this image to <code>/wp-content/themes/vigilance/images/top-banner</code>.', 'vigilance'),
					    	"std" => "",
					    	"type" => "text"),
        
        array(	"name" => __('Custom code', 'vigilance'),
					    	"id" => $shortname."_banner_custom",
								"desc" => __('Replace your top banner with custom code.<br /><strong>Note:</strong> The <em>Banner State</em> must be set to "Custom code" for this to work.', 'vigilance'),
					    	"std" => "",
					    	"type" => "textarea",
              	"options" => array(	"rows" => "5",
										   							"cols" => "40") ),
                       
        array(	"name" => __('Alert Box', 'vigilance'),
								"type" => "subhead"),
            
        array(	"name" => __('Alert Box On/Off', 'vigilance'),
								"id" => $shortname."_alertbox_state",
								"desc" => __('Toggle the alert box.', 'vigilance'),
			    			"std" => __('Off', 'vigilance'),
			    			"type" => "select",
			    			"options" => array( "off" => __('Off', 'vigilance'), "on" => __('On', 'vigilance'))),
              
        array(	"name" => __('Alert Title', 'vigilance'),
					    	"id" => $shortname."_alertbox_title",
              	"desc" => __('The title of your alert.', 'vigilance'),
					    	"std" => "",
					    	"type" => "text"),
        
        array(	"name" => __('Alert Message', 'vigilance'),
								"id" => $shortname."_alertbox_content",
								"desc" => __('Must use HTML in the message including <code>&#60;p&#62;</code> tags.', 'vigilance'),
								"std" => "",
								"type" => "textarea",
								"options" => array(	"rows" => "8",
										   							"cols" => "70") ),
                   
        array(	"name" => __('Sidebar Image', 'vigilance'),
								"type" => "subhead"),

				array(	"name" => __('Image state', 'vigilance'),
								"desc" => __('Place your images in the <code>/wp-content/themes/vigilance/images/sidebar</code> subdirectory and they will be added to the rotation. <br /><a href="http://themes.jestro.com/tutorials/vigilance.htm#options-banner">Read this for page and post specific images.</a>', 'vigilance'),
			    			"id" => $shortname."_sideimg_state",
			    			"std" => __('Rotating images', 'vigilance'),
			    			"type" => "select",
			    			"options" => array( "rotate" => __('Rotating images', 'vigilance'), "static" => __('Static image', 'vigilance'), "custom" => __('Custom code', 'vigilance'), "hide" => __('Do not show an image', 'vigilance'))),
        
        array(	"name" => __('Image height', 'vigilance'),
					    	"id" => $shortname."_sideimg_height",
              	"desc" => __('The height of your image. The width is fixed at 300px.', 'vigilance'),
					    	"std" => "250",
					    	"type" => "text"),
        
        array(	"name" => __('Image alt tag', 'vigilance'),
					    	"id" => $shortname."_sideimg_alt",
              	"desc" => __('The alt tag for your sidebar image(s). Will default to your blog title if left blank.', 'vigilance'),
					    	"std" => "",
					    	"type" => "text"),
        
        array(	"name" => __('Static image', 'vigilance'),
					    	"id" => $shortname."_sideimg_url",
              	"desc" => __('Replace your sidebar image with a static image.<br /><strong>Note:</strong> You must upload this image to <code>/wp-content/themes/vigilance/images/sidebar</code> <strong>and</strong> the <em>Image State</em> must be set to "Static Image"" for this to work.', 'vigilance'),
					    	"std" => "",
					    	"type" => "text"),
        
        array(	"name" => __('Image link', 'vigilance'),
					    	"id" => $shortname."_sideimg_link",
              	"desc" => __('Define a hyperlink for your sidebar image. If left empty the anchor tags will not be included.', 'vigilance'),
					    	"std" => "",
					    	"type" => "textarea",
              	"options" => array(	"rows" => "2",
										   							"cols" => "40") ),
              
        array(	"name" => __('Custom code', 'vigilance'),
					    	"id" => $shortname."_sideimg_custom",
								"desc" => __('Replace your sidebar image with custom code.<br /><strong>Note:</strong> The <em>Image State</em> must be set to "Custom code" for this to work.', 'vigilance'),
					    	"std" => "",
					    	"type" => "textarea",
              	"options" => array(	"rows" => "5",
										   							"cols" => "40") ),
     
        array(	"name" => __('Sidebar Feed Box', 'vigilance'),
              	"type" => "subhead"),
        
        array(	"name" => __('Feed box state', 'vigilance'),
              	"desc" => __('Enable or disable the feed box in the sidebar.', 'vigilance'),
					    	"id" => $shortname."_feed_state",
					    	"std" => __('Enabled', 'vigilance'),
					    	"type" => "select",
					    	"options" => array( "enabled" => __('Enabled', 'vigilance'), "disabled" => __('Disabled', 'vigilance'))),
              
        array(	"name" => __('Feed box title text', 'vigilance'),
					    	"id" => $shortname."_feed_title",
              	"desc" => __('Title of your feed box.', 'vigilance'),
					    	"std" => __('Get Free Updates', 'vigilance'),
					    	"type" => "text"),
            
        array(	"name" => __('Feed box intro text', 'vigilance'),
								"id" => $shortname."_feed_intro",
								"desc" => __('Enter your feed intro text here.', 'vigilance'),
								"std" => __('Get the latest and the greatest news delivered for free to your reader or your inbox:', 'vigilance'),
								"type" => "textarea",
								"options" => array(	"rows" => "5",
										   							"cols" => "40") ),
        
        array(	"name" => __('<a href="http://www.feedburner.com">Feedburner</a> email updates link', 'vigilance'),
								"id" => $shortname."_feed_email",
								"desc" => __('Enter your feed email link here. <strong>Do not paste the entire link code, just the URL.</strong><br /><del>&#60;a href=&#34;</del> <code>http://feedburner.google.com/fb/a/mailverify?uri=YOURFEEDID&amp;loc=en_US</code> <del>&#34;&#62;Subscribe to Your Feed by Email&#60;/a&#62;</del>', 'vigilance'),
								"std" => "http://feedburner.google.com/fb/a/mailverify?uri=YOURFEEDID&loc=en_US",
								"type" => "textarea",
								"options" => array(	"rows" => "2",
										   							"cols" => "80") ),

				array( 	"name" => __('Enable Twitter', 'vigilance'),
			    			"id" => $shortname."_twitter_toggle",
				  			"desc" => __('Hip to Twitter? Check this box.', 'vigilance'),
			    			"std" => "",
			    			"type" => "checkbox"),
										
				array(	"name" => __('Twitter updates link', 'vigilance'),
								"id" => $shortname."_twitter",
								"desc" => __('Enter your twitter link here.', 'vigilance'),
								"type" => "textarea",
								"options" => array(	"rows" => "2",
									   								"cols" => "80") ),		
				
        array(	"name" => __('Footer', 'vigilance'),
								"type" => "subhead"),

				array(	"name" => __('Copyright notice', 'vigilance'),
					    	"id" => $shortname."_copyright_name",
              	"desc" => __('Enter your copyright info above.', 'vigilance'),
					    	"std" => __('Your Name Here', 'vigilance'),
					    	"type" => "text"),			
				
				array(	"name" => __('Stats code', 'vigilance'),
								"id" => $shortname."_stats_code",
								"desc" => __('If you use Google Analytics or need any other tracking script in your footer just copy and paste it here.<br /> The script will be inserted before the closing <code>&#60;/body&#62;</code> tag.', 'vigilance'),
								"std" => "",
								"type" => "textarea",
								"options" => array(	"rows" => "5",
										   							"cols" => "40") ),
		  );
?>